-- CreateEnum
CREATE TYPE "TIPO_USUARIO" AS ENUM ('FAZENDEIRO', 'ADMIN', 'VETERINARIO');

-- CreateEnum
CREATE TYPE "TIPO_REMEDIO" AS ENUM ('SUPLEMENTO', 'REMEDIO', 'VERMIFUGO', 'VACINA');

-- CreateTable
CREATE TABLE "USUARIO" (
    "ID" BIGSERIAL NOT NULL,
    "NOME" TEXT NOT NULL,
    "EMAIL" TEXT,
    "SENHA" TEXT NOT NULL,
    "TELEFONE" TEXT NOT NULL,
    "ENDERECO" TEXT,
    "PERFIL_USUARIO" "TIPO_USUARIO" NOT NULL DEFAULT 'FAZENDEIRO',

    CONSTRAINT "USUARIO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "PROPRIEDADE" (
    "ID" BIGSERIAL NOT NULL,
    "NOME" TEXT NOT NULL,
    "LAT" TEXT,
    "LNG" TEXT,
    "USUARIO_ID" BIGINT NOT NULL,

    CONSTRAINT "PROPRIEDADE_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "VACINA" (
    "ID" BIGSERIAL NOT NULL,
    "NOME" TEXT NOT NULL,
    "FABRICANTE" TEXT,
    "COMPOSICAO" TEXT,
    "POSOLOGIA" TEXT,
    "LOTE" TEXT,
    "FRASCO_ML" TEXT,
    "NFE_NUMERO" TEXT,
    "NFE_CHAVE" TEXT,
    "TIPO_REMERDIO" "TIPO_REMEDIO" NOT NULL DEFAULT 'REMEDIO',

    CONSTRAINT "VACINA_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "ANIMAL" (
    "ID" BIGSERIAL NOT NULL,
    "NOME" TEXT NOT NULL,
    "SEXO" TEXT NOT NULL,
    "DATA_NASCIMENTO" DATE NOT NULL,
    "CATEGORIA" TEXT,
    "PESO" TEXT,
    "STATUS" TEXT NOT NULL,
    "USUARIO_ID" BIGINT NOT NULL,

    CONSTRAINT "ANIMAL_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "VACINACAO" (
    "ID" BIGSERIAL NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DOSE_APLICADA" TEXT,
    "VIA_APLICADA" TEXT,
    "VACINA_ID" BIGINT NOT NULL,
    "ANIMAL_ID" BIGINT NOT NULL,

    CONSTRAINT "VACINACAO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "NOTA_FISCAL" (
    "ID" BIGSERIAL NOT NULL,
    "NUMERO" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "VALOR_TOTAL" TEXT NOT NULL,
    "STATUS_VALIDACAO" BOOLEAN NOT NULL,
    "MENSAGEM_VALIDACAO" TEXT NOT NULL,

    CONSTRAINT "NOTA_FISCAL_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "NOTA_FISCAL_VACINACAO" (
    "VACINACAO_ID" BIGINT NOT NULL,
    "NOTA_FISCAL_ID" BIGINT NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "NOTA_FISCAL_VACINACAO_VACINACAO_ID_key" ON "NOTA_FISCAL_VACINACAO"("VACINACAO_ID");

-- AddForeignKey
ALTER TABLE "PROPRIEDADE" ADD CONSTRAINT "PROPRIEDADE_USUARIO_ID_fkey" FOREIGN KEY ("USUARIO_ID") REFERENCES "USUARIO"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ANIMAL" ADD CONSTRAINT "ANIMAL_USUARIO_ID_fkey" FOREIGN KEY ("USUARIO_ID") REFERENCES "USUARIO"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VACINACAO" ADD CONSTRAINT "VACINACAO_VACINA_ID_fkey" FOREIGN KEY ("VACINA_ID") REFERENCES "VACINA"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VACINACAO" ADD CONSTRAINT "VACINACAO_ANIMAL_ID_fkey" FOREIGN KEY ("ANIMAL_ID") REFERENCES "ANIMAL"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NOTA_FISCAL_VACINACAO" ADD CONSTRAINT "NOTA_FISCAL_VACINACAO_VACINACAO_ID_fkey" FOREIGN KEY ("VACINACAO_ID") REFERENCES "VACINACAO"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NOTA_FISCAL_VACINACAO" ADD CONSTRAINT "NOTA_FISCAL_VACINACAO_NOTA_FISCAL_ID_fkey" FOREIGN KEY ("NOTA_FISCAL_ID") REFERENCES "NOTA_FISCAL"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
