-- CreateTable
CREATE TABLE "VETERINARIO" (
    "USUARIO_ID" BIGINT NOT NULL,
    "CRMV" TEXT NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "VETERINARIO_USUARIO_ID_key" ON "VETERINARIO"("USUARIO_ID");

-- AddForeignKey
ALTER TABLE "VETERINARIO" ADD CONSTRAINT "VETERINARIO_USUARIO_ID_fkey" FOREIGN KEY ("USUARIO_ID") REFERENCES "USUARIO"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
